import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:grin_tech/view_model/methods.dart';
import 'package:grin_tech/model/model.dart';

class Page1 extends StatefulWidget {
  const Page1({Key? key}) : super(key: key);

  @override
  State<Page1> createState() => _Page1State();
}

class _Page1State extends State<Page1> {
  String? userDetails;
  List<Data> dataList = [];
  @override
  void initState() {
    super.initState();

    getUserDetail();
  }

  Future<void> getUserDetail() async {
    String page = "1";
    var response = await ApiCall().userDetail(page);
    if (response.statusCode == 200) {
      var parsedJson = jsonDecode(response.body);
      Autogenerated autogenerated = Autogenerated.fromJson(parsedJson);

      if (autogenerated.data != null) {
        setState(() {
          // Store the first 5 user data entries in dataList
          dataList = autogenerated.data!.take(5).toList();
        });
      }
    } else {
      // Handle error scenario
      print('Failed to load user details: ${response.statusCode}');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Page 1',
          style: TextStyle(color: Colors.white),
        ),
        backgroundColor: Color(0xFF012B5B),
      ),
      body: RefreshIndicator(
        onRefresh: () async {
          setState(() {
            dataList.clear();
          });
          // Refresh logic here
          await getUserDetail();
        },
        child: dataList.isEmpty
            ? Center(
                child: CircularProgressIndicator(),
              )
            : ListView.builder(
                itemCount: dataList.length,
                itemBuilder: (context, index) {
                  Data userData = dataList[index];
                  return Card(
                    margin: EdgeInsets.all(8.0),
                    child: ListTile(
                      leading: CircleAvatar(
                        backgroundImage: NetworkImage(userData.avatar ?? ''),
                      ),
                      title: Text(
                          '${userData.firstName ?? ''} ${userData.lastName ?? ''}'),
                      subtitle: Text(userData.email ?? ''),
                    ),
                  );
                },
              ),
      ),
    );
  }
}
